name: turnable_page
description: "Realistic page-flipping widget for Flutter with smooth animations, interactive content, and smart gesture detection."
version: 1.0.4
homepage: https://saeed-flutter.vercel.app
repository: https://github.com/saeedahmed725/turnable_page

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0